# Generated by Django 3.1.5 on 2021-02-02 00:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appFood', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_name', models.CharField(max_length=200)),
                ('directions', models.TextField(max_length=1000)),
            ],
            options={
                'ordering': ['recipe_name'],
            },
        ),
        migrations.CreateModel(
            name='StorageItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=250)),
                ('storage_type', models.PositiveSmallIntegerField(choices=[(1, 'Room temp storage'), (2, 'Fridge - cold storage'), (3, 'Freezer - really cold storage')], default=1)),
                ('quant_onHand', models.PositiveIntegerField(default=0)),
                ('quant_amount', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'ordering': ['item_name'],
            },
        ),
        migrations.CreateModel(
            name='RecipeCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.PositiveSmallIntegerField(choices=[(1, 'Main dishes'), (2, 'Breakfast'), (3, 'Lunch'), (4, 'Soups'), (5, 'American or home style meals'), (6, 'Italian'), (7, 'Mexican'), (8, 'Asian, Chinese, Japanese, etc'), (9, 'Russian'), (10, 'European, any country'), (11, 'Desserts and treats'), (12, 'Other, anything')], default=1)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appFood.recipe')),
            ],
            options={
                'ordering': ['category_name'],
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient_name', models.CharField(max_length=250)),
                ('measurement_units', models.CharField(max_length=50)),
                ('measurement_quantity', models.CharField(max_length=50)),
                ('recipe', models.ManyToManyField(to='appFood.Recipe')),
            ],
            options={
                'ordering': ['ingredient_name'],
            },
        ),
    ]
