# Generated by Django 3.1.5 on 2021-02-11 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appFood', '0002_ingredient_recipe_recipecategory_storageitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storageitem',
            name='quant_onHand',
            field=models.IntegerField(default=0),
        ),
    ]
