# Generated by Django 3.1.5 on 2021-02-14 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appFood', '0003_auto_20210210_2014'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='category_name',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Main dishes'), (2, 'Breakfast'), (3, 'Lunch'), (4, 'Soups'), (5, 'American or home style meals'), (6, 'Italian'), (7, 'Mexican'), (8, 'Asian, Chinese, Japanese, etc'), (9, 'Russian'), (10, 'European, any country'), (11, 'Desserts and treats'), (12, 'Other, anything')], default=1),
        ),
        migrations.DeleteModel(
            name='RecipeCategory',
        ),
    ]
