# Generated by Django 3.1.5 on 2021-02-17 23:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appFood', '0005_auto_20210217_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='recipe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appFood.recipe'),
        ),
    ]
