# Generated by Django 3.1.5 on 2021-02-18 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appFood', '0006_event_recipe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='description',
        ),
        migrations.RemoveField(
            model_name='event',
            name='title',
        ),
    ]
