# Generated by Django 3.1.5 on 2021-02-21 06:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appFood', '0007_auto_20210217_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='start_time',
            field=models.DateTimeField(default=datetime.date.today),
        ),
        migrations.DeleteModel(
            name='Event',
        ),
    ]
