# Generated by Django 3.1.5 on 2021-02-21 09:46

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appFood', '0008_auto_20210220_2331'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='start_time',
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(default=datetime.date.today)),
                ('recipe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appFood.recipe')),
            ],
        ),
    ]
