# Generated by Django 3.1.5 on 2021-02-22 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appFood', '0009_auto_20210221_0246'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Event',
            new_name='Meal',
        ),
    ]
