# Generated by Django 3.1.5 on 2021-03-08 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appFood', '0015_storageitem_measurement_units'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storageitem',
            old_name='measurement_units',
            new_name='container_type',
        ),
    ]
